

services:
  db:
    image: mysql:8.0
    container_name: medicare_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medicare_unified
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql

  admin:
    build: .
    container_name: admin_service
    command: python -m app.app_admin
    ports:
      - "5003:5003"
    env_file:
      - .env
    depends_on:
      - db

  medecin:
    build: .
    container_name: medecin_service
    command: python -m app.main_medecin
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - db

  patient:
    build: .
    container_name: patient_service
    command: python -m app.patient_app
    ports:
      - "5002:5002"
    env_file:
      - .env
    depends_on:
      - db

  app_general:
    build: .
    container_name: app_general
    command: python app.py
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
